# Generated by Django 3.1.5 on 2021-03-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='amount_accuracy',
            field=models.CharField(default='X', max_length=1),
        ),
    ]
