# Generated by Django 3.1.5 on 2021-03-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='storage_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
