# Generated by Django 3.1.5 on 2021-02-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
