# Generated by Django 3.1.5 on 2021-03-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0002_auto_20210301_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='storage_place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
