# Generated by Django 3.1.5 on 2021-02-15 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('INC', 'Inactive'), ('ACT', 'Active'), ('ASS', 'Assembling'), ('RDY', 'Ready'), ('ARC', 'Archived'), ('CNF', 'Confirmed'), ('CND', 'Canceled')], default='INC', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_limit', models.DecimalField(decimal_places=2, default=10, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('product_id', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount', models.IntegerField(default=0)),
                ('coefficient', models.DecimalField(decimal_places=2, default=None, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100)),
                ('var', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt', models.CharField(max_length=100, unique=True)),
                ('bb', models.FloatField()),
                ('v', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cella.test1')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CRT', 'Create'), ('DCT', 'Deactivate'), ('ACT', 'Activate'), ('STP', 'Set price'), ('STA', 'Set amount'), ('UPF', 'Update fields'), ('SCT', 'Set coefficient'), ('SCY', 'Set category'), ('BLS', 'Build set')], max_length=3)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=300, null=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specification_actions', to='cella.operator')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specification_actions', to='cella.specification')),
            ],
        ),
        migrations.AddField(
            model_name='specification',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specifications', to='cella.specificationcategory'),
        ),
        migrations.CreateModel(
            name='ResourceSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_specs', to='cella.resource')),
                ('specification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='res_specs', to='cella.specification')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cella.resource')),
            ],
            options={
                'ordering': ['time_stamp'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CRT', 'Create'), ('UPF', 'Update fields'), ('STC', 'Set cost'), ('STA', 'Set amount'), ('VYC', 'Verify cost'), ('CMT', 'Change amount')], max_length=3)),
                ('value', models.CharField(max_length=300, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_actions', to='cella.operator')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_actions', to='cella.resource')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='cella.resourceprovider'),
        ),
        migrations.CreateModel(
            name='OrderSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('assembled', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_specification', to='cella.order')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_specification', to='cella.specification')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CRT', 'Create'), ('CFM', 'Confirm'), ('CNL', 'Cancel'), ('ACT', 'Activate'), ('DCT', 'Deactivate'), ('ASS', 'Assembling'), ('PRP', 'Preparing'), ('ARC', 'Archivation'), ('ASP', 'Assembling specification'), ('DSS', 'Disassembling specification')], max_length=3)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(default=None, max_length=300, null=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_actions', to='cella.operator')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_actions', to='cella.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cella.ordersource'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('direction', models.CharField(choices=[('RAD', 'Resource add')], default='RAD', max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cella.operator')),
            ],
        ),
    ]
