# Generated by Django 3.1.5 on 2021-02-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderspecification',
            name='assembled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderspecification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_specification', to='cella.order'),
        ),
        migrations.AlterField(
            model_name='orderspecification',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_specification', to='cella.specification'),
        ),
    ]
