# Generated by Django 3.1.5 on 2021-02-07 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0002_auto_20210206_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='active',
        ),
        migrations.RemoveField(
            model_name='order',
            name='archived',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INC', 'Inactive'), ('ACT', 'Active'), ('ASS', 'Assembling'), ('RDY', 'Ready'), ('ARC', 'Archived'), ('CNF', 'Confirmed'), ('CND', 'Canceled')], default='INC', max_length=3),
        ),
        migrations.AlterField(
            model_name='orderaction',
            name='action_type',
            field=models.CharField(choices=[('CRT', 'Create'), ('CFM', 'Confirm'), ('CNL', 'Cancel'), ('ACT', 'Activate'), ('DCT', 'Deactivate'), ('ASS', 'Assembling'), ('PRP', 'Preparing'), ('ARC', 'Archivation'), ('ASP', 'Assembling specification'), ('DSS', 'Disassembling specification')], max_length=3),
        ),
    ]
