# Generated by Django 3.1.5 on 2021-02-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0003_auto_20210207_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(default='Amazon', max_length=100),
        ),
    ]
