# Generated by Django 3.1.5 on 2021-02-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cella', '0004_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='specification',
            name='storage_amount',
            field=models.IntegerField(default=0),
        ),
    ]
