# Generated by Django 3.1.5 on 2021-03-13 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cella', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('amount_limit', models.DecimalField(decimal_places=2, default=10, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storage_place', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comment', models.CharField(max_length=400, null=True)),
                ('time_stamp', models.DateField(null=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.resourceprovider')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('verified', models.BooleanField(default=False)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource')),
            ],
            options={
                'ordering': ['time_stamp'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CRT', 'Create'), ('UPF', 'Update fields'), ('STC', 'Set cost'), ('STA', 'Set amount'), ('VYC', 'Verify cost'), ('CMT', 'Change amount')], max_length=3)),
                ('value', models.CharField(max_length=300, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resource_actions', to='cella.operator')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_actions', to='resources.resource')),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourceprovider'),
        ),
    ]
