# Generated by Django 3.1.5 on 2021-03-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='storage_place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
