# Generated by Django 3.1.5 on 2021-03-16 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaction',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
