# Generated by Django 3.1.5 on 2021-03-19 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedelivery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
