# Generated by Django 3.1.5 on 2021-03-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourcedelivery_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='comment',
        ),
    ]
