# Generated by Django 3.1.5 on 2021-03-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20210316_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcedelivery',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
