# Generated by Django 3.1.5 on 2021-03-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specification', '0002_auto_20210319_2122'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INC', 'Inactive'), ('ARC', 'Archived'), ('CNF', 'Confirmed'), ('CND', 'Canceled')], default='INC', max_length=3),
        ),
        migrations.AlterField(
            model_name='orderspecification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_specifications', to='order.order'),
        ),
        migrations.AlterField(
            model_name='orderspecification',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_specifications', to='specification.specification'),
        ),
    ]
